// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP0abZSCXrFZtNuQIKNR-XszLPcF4rWx0',
    appId: '1:869878965251:web:b01d565772b40133879a36',
    messagingSenderId: '869878965251',
    projectId: 'active-app-12345',
    authDomain: 'active-app-12345.firebaseapp.com',
    storageBucket: 'active-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Dmj8EUWAOGbEX4EiFueU9j9jU4Y0wDQ',
    appId: '1:869878965251:android:0253f1e1bc61c37f879a36',
    messagingSenderId: '869878965251',
    projectId: 'active-app-12345',
    storageBucket: 'active-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1MJTNOOuDD53ivBeKM_U5s4VbzrWRkM',
    appId: '1:869878965251:ios:b3f787d0e1b3d501879a36',
    messagingSenderId: '869878965251',
    projectId: 'active-app-12345',
    storageBucket: 'active-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.active',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1MJTNOOuDD53ivBeKM_U5s4VbzrWRkM',
    appId: '1:869878965251:ios:b3f787d0e1b3d501879a36',
    messagingSenderId: '869878965251',
    projectId: 'active-app-12345',
    storageBucket: 'active-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.active',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP0abZSCXrFZtNuQIKNR-XszLPcF4rWx0',
    appId: '1:869878965251:web:bfb8c3a0080cf5ef879a36',
    messagingSenderId: '869878965251',
    projectId: 'active-app-12345',
    authDomain: 'active-app-12345.firebaseapp.com',
    storageBucket: 'active-app-12345.firebasestorage.app',
  );
}
