import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'core/di/injection_container.dart' as di;
import 'presentation/providers/activity_provider.dart';
import 'presentation/providers/auth_provider.dart';
import 'presentation/providers/sync_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Dependency Injection
  await di.init();

  // Initialize Firebase infrastructure
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => di.sl<AppAuthProvider>()),
        ChangeNotifierProvider(create: (_) => di.sl<ActivityController>()..loadActivities()),
        ChangeNotifierProxyProvider<AppAuthProvider, SyncController>(
          create: (_) => di.sl<SyncController>(),
          update: (_, auth, sync) {
            if (sync != null) {
              sync.init(auth.userId);
            }
            return sync!;
          },
        ),
      ],
      child: const ActiveApp(),
    ),
  );
}

class ActiveApp extends StatelessWidget {
  const ActiveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Active',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple)),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Active App Initialized', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
              const SizedBox(height: 20),
              Consumer<AppAuthProvider>(
                builder: (context, auth, _) {
                  return Text('User ID: ${auth.userId ?? "Not logged in"}');
                },
              ),
              Consumer<SyncController>(
                builder: (context, sync, _) {
                  return Text('Sync Status: ${sync.isSyncing ? "Syncing..." : "Idle"}');
                },
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () => context.read<AppAuthProvider>().signInAnonymously(),
                child: const Text('Sign In Anonymously'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
