import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase infrastructure
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ActiveApp());
}

class ActiveApp extends StatelessWidget {
  const ActiveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(body: Center(child: Text('Active App Initialized'))),
    );
  }
}
