import '../../domain/entities/activity.dart';

final List<Activity> kTestActivities = [
  // --- WORK BRANCH ---
  Activity(
    id: 'work-root',
    name: 'Work',
    description: 'All professional tasks',
    status: ActivityStatus.idle,
    totalSeconds: 3600,
    type: ActivityType.timeBased,
    parentId: null,
    childrenIds: const ['deep-work', 'meetings', 'admin'],
    createdAt: DateTime(2026, 1, 1),
    updatedAt: DateTime(2026, 1, 1),
  ),
  Activity(
    id: 'deep-work',
    name: 'Deep Work',
    description: 'Focused coding and design',
    status: ActivityStatus.idle,
    totalSeconds: 7200,
    type: ActivityType.timeBased,
    parentId: 'work-root',
    childrenIds: const ['frontend-task', 'backend-refactor'],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
    goalSeconds: 14400,
  ),
  Activity(
    id: 'frontend-task',
    name: 'Frontend Feature',
    status: ActivityStatus.idle,
    totalSeconds: 1800,
    type: ActivityType.timeBased,
    parentId: 'deep-work',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),
  Activity(
    id: 'backend-refactor',
    name: 'Backend Refactor',
    status: ActivityStatus.idle,
    totalSeconds: 2400,
    type: ActivityType.timeBased,
    parentId: 'deep-work',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),
  Activity(
    id: 'meetings',
    name: 'Meetings',
    status: ActivityStatus.idle,
    totalSeconds: 3600,
    type: ActivityType.timeBased,
    parentId: 'work-root',
    childrenIds: const ['standup', 'planning'],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),
  Activity(
    id: 'standup',
    name: 'Daily Standup',
    status: ActivityStatus.idle,
    totalSeconds: 900,
    type: ActivityType.timeBased,
    parentId: 'meetings',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),
  Activity(
    id: 'planning',
    name: 'Sprint Planning',
    status: ActivityStatus.idle,
    totalSeconds: 2700,
    type: ActivityType.timeBased,
    parentId: 'meetings',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),
  Activity(
    id: 'admin',
    name: 'Admin Tasks',
    status: ActivityStatus.idle,
    totalSeconds: 600,
    type: ActivityType.timeBased,
    parentId: 'work-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 2),
    updatedAt: DateTime(2026, 1, 2),
  ),

  // --- FITNESS BRANCH ---
  Activity(
    id: 'fitness-root',
    name: 'Fitness',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.timeBased,
    parentId: null,
    childrenIds: const ['gym-session', 'morning-run', 'yoga'],
    createdAt: DateTime(2026, 1, 1),
    updatedAt: DateTime(2026, 1, 1),
  ),
  Activity(
    id: 'gym-session',
    name: 'Gym',
    status: ActivityStatus.idle,
    totalSeconds: 4500,
    type: ActivityType.timeBased,
    parentId: 'fitness-root',
    childrenIds: const ['chest-day', 'leg-day'],
    createdAt: DateTime(2026, 1, 3),
    updatedAt: DateTime(2026, 1, 3),
  ),
  Activity(
    id: 'chest-day',
    name: 'Chest & Tri',
    status: ActivityStatus.idle,
    totalSeconds: 2000,
    type: ActivityType.timeBased,
    parentId: 'gym-session',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 3),
    updatedAt: DateTime(2026, 1, 3),
  ),
  Activity(
    id: 'leg-day',
    name: 'Leg Day',
    status: ActivityStatus.idle,
    totalSeconds: 2500,
    type: ActivityType.timeBased,
    parentId: 'gym-session',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 3),
    updatedAt: DateTime(2026, 1, 3),
  ),
  Activity(
    id: 'morning-run',
    name: 'Running',
    status: ActivityStatus.idle,
    totalSeconds: 1800,
    type: ActivityType.timeBased,
    parentId: 'fitness-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 3),
    updatedAt: DateTime(2026, 1, 3),
    goalSeconds: 3600,
  ),
  Activity(
    id: 'yoga',
    name: 'Yoga',
    status: ActivityStatus.idle,
    totalSeconds: 1200,
    type: ActivityType.timeBased,
    parentId: 'fitness-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 3),
    updatedAt: DateTime(2026, 1, 3),
  ),

  // --- COUNT-BASED BRANCH ---
  Activity(
    id: 'count-root',
    name: 'Tracking Metrics',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.countBased,
    parentId: null,
    childrenIds: const ['pushups', 'water', 'pages', 'coffee'],
    createdAt: DateTime(2026, 1, 1),
    updatedAt: DateTime(2026, 1, 1),
  ),
  Activity(
    id: 'pushups',
    name: 'Pushups',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.countBased,
    parentId: 'count-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 4),
    updatedAt: DateTime(2026, 1, 4),
  ),
  Activity(
    id: 'water',
    name: 'Water Glasses',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.countBased,
    parentId: 'count-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 4),
    updatedAt: DateTime(2026, 1, 4),
  ),
  Activity(
    id: 'pages',
    name: 'Pages Read',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.countBased,
    parentId: 'count-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 4),
    updatedAt: DateTime(2026, 1, 4),
  ),
  Activity(
    id: 'coffee',
    name: 'Coffee Cups',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.countBased,
    parentId: 'count-root',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 4),
    updatedAt: DateTime(2026, 1, 4),
  ),

  // --- LEARNING BRANCH ---
  Activity(
    id: 'learning-root',
    name: 'Learning',
    status: ActivityStatus.idle,
    totalSeconds: 0,
    type: ActivityType.timeBased,
    parentId: null,
    childrenIds: const ['flutter-study', 'rust-study', 'design-study'],
    createdAt: DateTime(2026, 1, 1),
    updatedAt: DateTime(2026, 1, 1),
  ),
  Activity(
    id: 'flutter-study',
    name: 'Flutter',
    status: ActivityStatus.idle,
    totalSeconds: 5000,
    type: ActivityType.timeBased,
    parentId: 'learning-root',
    childrenIds: const ['widget-basics', 'state-management', 'animations'],
    createdAt: DateTime(2026, 1, 5),
    updatedAt: DateTime(2026, 1, 5),
  ),
  Activity(
    id: 'widget-basics',
    name: 'Widget Basics',
    status: ActivityStatus.idle,
    totalSeconds: 1000,
    type: ActivityType.timeBased,
    parentId: 'flutter-study',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 5),
    updatedAt: DateTime(2026, 1, 5),
  ),
  Activity(
    id: 'state-management',
    name: 'State Management',
    status: ActivityStatus.idle,
    totalSeconds: 2000,
    type: ActivityType.timeBased,
    parentId: 'flutter-study',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 5),
    updatedAt: DateTime(2026, 1, 5),
  ),
  Activity(
    id: 'animations',
    name: 'Animations',
    status: ActivityStatus.idle,
    totalSeconds: 2000,
    type: ActivityType.timeBased,
    parentId: 'flutter-study',
    childrenIds: const [],
    createdAt: DateTime(2026, 1, 5),
    updatedAt: DateTime(2026, 1, 5),
  ),

  // --- FILLING UP TO 50 ---
  ...List.generate(
    26,
    (index) => Activity(
      id: 'extra-activity-${index + 1}',
      name: 'Activity ${index + 1}',
      status: ActivityStatus.idle,
      totalSeconds: (index + 1) * 100,
      type: index % 2 == 0 ? ActivityType.timeBased : ActivityType.countBased,
      parentId: null,
      childrenIds: const [],
      createdAt: DateTime(2026, 1, 6),
      updatedAt: DateTime(2026, 1, 6),
    ),
  ),
];
